volumes:
  images-data:

services:
  api:
    user: "0"
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      Smtp__Host: smtp.gmail.com
      Smtp__Port: 587
      Smtp__Username: ${SMTP_USERNAME}
      Smtp__Password: ${SMTP_PASSWORD}
      Smtp__FromEmail: ${SMTP_FROM_EMAIL}
      Smtp__FromName: ${SMTP_FROM_NAME}
      ConnectionStrings__Campus4U: ${CONNECTION_STRING}
      Storage__RootPath: /data/images
      Storage__MaxBytes: 10485760
      Storage__AllowedTypes__0: image/jpeg
      Storage__AllowedTypes__1: image/png
      Storage__AllowedTypes__2: image/webp
    volumes:
      - images-data:/data/images